package com.puntbyte.dbml.parser

import com.intellij.lang.ASTNode
import com.intellij.lang.ParserDefinition
import com.intellij.lang.PsiParser
import com.intellij.lexer.Lexer
import com.intellij.openapi.project.Project
import com.intellij.psi.FileViewProvider
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.psi.tree.IFileElementType
import com.intellij.psi.tree.TokenSet
import com.puntbyte.dbml.core.DbmlLanguage
import com.puntbyte.dbml.lexer.DbmlLexerAdapter
import com.puntbyte.dbml.psi.DbmlFile
import com.puntbyte.dbml.psi.DbmlTypes // Generated by Grammar-Kit

class DbmlParserDefinition : ParserDefinition {

  override fun getFileNodeType(): IFileElementType = FILE

  override fun createLexer(project: Project): Lexer = DbmlLexerAdapter()

  // FIX: Use the generated Parser, not a manual loop
  override fun createParser(project: Project): PsiParser = DbmlParser()

  // FIX: Use the generated Factory to create specific PSI elements (TableIdentifier, etc.)
  override fun createElement(node: ASTNode): PsiElement = DbmlTypes.Factory.createElement(node)

  override fun createFile(viewProvider: FileViewProvider): PsiFile = DbmlFile(viewProvider)

  override fun getCommentTokens(): TokenSet = TokenSet.create(DbmlTypes.LINE_COMMENT)

  override fun getStringLiteralElements(): TokenSet = TokenSet.create(
    DbmlTypes.STRING,
    DbmlTypes.MULTI_STRING,
    DbmlTypes.EXPRESSION
  )

  companion object {
    val FILE = IFileElementType(DbmlLanguage)
  }
}