{
  parserClass="com.puntbyte.dbml.parser.DbmlParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Dbml"
  psiImplClassSuffix="Impl"
  psiPackage="com.puntbyte.dbml.psi"
  psiImplPackage="com.puntbyte.dbml.psi.impl"
  psiImplUtilClass="com.puntbyte.dbml.psi.impl.DbmlPsiImplUtil"

  elementTypeHolderClass="com.puntbyte.dbml.psi.DbmlTypes"
  elementTypeClass="com.puntbyte.dbml.psi.DbmlElementType"
  tokenTypeClass="com.puntbyte.dbml.psi.DbmlElementType"

  tokens=[
    // Structural
    L_BRACE='{' R_BRACE='}' L_BRACKET='[' R_BRACKET=']' L_PAREN='(' R_PAREN=')'
    COLON=':' DOT='.' COMMA=',' TILDE='~'

    // Operators
    OP_ONE_MANY='<' OP_MANY_ONE='>' OP_ONE_ONE='-' OP_MANY_MANY='<>'

    // Keywords
    KW_TABLE KW_GROUP KW_PARTIAL KW_PROJECT KW_REF KW_ENUM
    KW_NOTE KW_INDEXES KW_CHECKS KW_AS

    // Data
    BOOLEAN NUMBER STRING MULTI_STRING COLOR NULL
    EXPRESSION IDENTIFIER_TOKEN

    // Contextual tokens (from Lexer)
    DATA_TYPE_TOKEN SETTING_KEY SETTING_VAL

    // Comments
    LINE_COMMENT BLOCK_COMMENT DOC_COMMENT
  ]
}

DbmlFile ::= TopLevelItem*

private TopLevelItem ::= ProjectDefinition
  | EnumDefinition
  | TableDefinition
  | ReferenceDefinition
  | GroupDefinition
  | PartialDefinition
  | StickyNoteDefinition
  | Comment
  { recoverWhile=TopLevelRecover }

private TopLevelRecover ::= !(KW_TABLE | KW_ENUM | KW_PROJECT | KW_REF | KW_GROUP | KW_PARTIAL | KW_NOTE)

// ---- 1. PROJECT ----
ProjectDefinition ::= ProjectKeyword Identifier? ProjectBlock { pin=1 }
ProjectKeyword ::= KW_PROJECT
ProjectBlock ::= L_BRACE ProjectContent* (NoteDefinition)? R_BRACE { pin=1 }
ProjectContent ::= MapEntry | Comment


// ---- 2. ENUM ----
EnumDefinition ::= EnumKeyword EnumIdentifier EnumBlock { pin=1 }
EnumKeyword ::= KW_ENUM
EnumIdentifier ::= Identifier (DOT Identifier)?
EnumBlock ::= L_BRACE EnumValue* R_BRACE { pin=1 }
EnumValue ::= (Identifier | STRING) SettingBlock? { recoverWhile=EnumRecover }
private EnumRecover ::= !(R_BRACE | IDENTIFIER_TOKEN | STRING)


// ---- 3. TABLE ----
TableDefinition ::= TableKeyword TableIdentifier AliasClause? SettingBlock? TableBlock {
   pin=1
   implements="com.intellij.psi.PsiNameIdentifierOwner"
   mixin="com.puntbyte.dbml.psi.impl.DbmlTableDefinitionMixin"
   stubClass="com.puntbyte.dbml.psi.stubs.DbmlTableStub"
   elementTypeFactory="com.puntbyte.dbml.psi.stubs.DbmlStubTypes.getFactory"
}
TableKeyword ::= KW_TABLE
TableIdentifier ::= Identifier (DOT Identifier)?
TableBlock ::= L_BRACE TableContent* R_BRACE { pin=1 }

private TableContent ::=
    IndexDefinition
  | CheckDefinition
  | NoteDefinition
  | ReferenceDefinition
  | PartialReference
  | MapEntry
  | ColumnDefinition
  | Comment
  { recoverWhile=TableContentRecover }

// Ensures recovery doesn't skip column names like 'name' or 'type'
private TableContentRecover ::= !(R_BRACE | IDENTIFIER_TOKEN | DATA_TYPE_TOKEN | SETTING_KEY | SETTING_VAL | KW_NOTE | KW_REF | KW_INDEXES | KW_CHECKS | TILDE)

AliasClause ::= AliasKeyword Identifier
AliasKeyword ::= KW_AS


// ---- 4. PARTIAL ----
PartialDefinition ::= PartialKeyword PartialIdentifier SettingBlock? PartialBlock {
    pin=1
    implements="com.intellij.psi.PsiNameIdentifierOwner"
    methods=[getName setName getNameIdentifier]
}
PartialKeyword ::= KW_PARTIAL
PartialIdentifier ::= Identifier
PartialBlock ::= L_BRACE PartialContent* R_BRACE { pin=1 }
private PartialContent ::= IndexDefinition | NoteDefinition | ColumnDefinition | Comment { recoverWhile=TableContentRecover }

PartialReference ::= TILDE PartialIdentifier


// ---- 5. COLUMN ----
ColumnDefinition ::= Identifier ColumnType SettingBlock? { pin=1 }
ColumnType ::= DataType (L_PAREN DataLimit R_PAREN)?
DataType ::= Identifier
DataLimit ::= NUMBER (COMMA NUMBER)?


// ---- 6. INDEXES ----
IndexDefinition ::= IndexKeyword IndexBlock { pin=1 }
IndexKeyword ::= KW_INDEXES
IndexBlock ::= L_BRACE IndexItem* R_BRACE { pin=1 }
IndexItem ::= IndexExpression SettingBlock? { recoverWhile=BlockItemRecover }
IndexExpression ::= Identifier | L_PAREN ColumnList R_PAREN | ExpressionWrapper


// ---- 7. CHECKS ----
CheckDefinition ::= CheckKeyword CheckBlock { pin=1 }
CheckKeyword ::= KW_CHECKS
CheckBlock ::= L_BRACE CheckItem* R_BRACE { pin=1 }
CheckItem ::= ExpressionWrapper SettingBlock? { recoverWhile=BlockItemRecover }

private BlockItemRecover ::= !(R_BRACE | IDENTIFIER_TOKEN | EXPRESSION | L_PAREN)


// ---- 8. NOTES ----
StickyNoteDefinition ::= NoteKeyword Identifier? SettingBlock? NoteBlock { pin=1 }

NoteDefinition ::= NoteKeyword NoteDeclaration { pin=1 }
private NoteDeclaration ::= NoteBlock | (COLON (STRING | MULTI_STRING))
NoteKeyword ::= KW_NOTE
NoteBlock ::= L_BRACE (STRING | MULTI_STRING) R_BRACE { pin=1 }


// ---- 9. REFS ----
ReferenceDefinition ::= ReferenceKeyword Identifier? ReferenceContent { pin=1 }
ReferenceKeyword ::= KW_REF
ReferenceContent ::= ReferenceBlock | (COLON ReferenceExpression)
ReferenceBlock ::= L_BRACE ReferenceExpression R_BRACE { pin=1 }

ReferenceExpression ::= ColumnReference RelationOperator ColumnReference SettingBlock?


// ---- 10. GROUPS ----
GroupDefinition ::= GroupKeyword Identifier SettingBlock? GroupBlock { pin=1 }
GroupKeyword ::= KW_GROUP
GroupBlock ::= L_BRACE GroupContent* R_BRACE { pin=1 }
GroupContent ::= TableIdentifier | NoteDefinition | Comment { recoverWhile=GroupContentRecover }

private GroupContentRecover ::= !(R_BRACE | IDENTIFIER_TOKEN | KW_NOTE)


// ---- 11. SETTINGS ----
SettingBlock ::= L_BRACKET SettingList R_BRACKET { pin=1 }
SettingList ::= SettingContent (COMMA SettingContent)*
SettingContent ::= MapEntry | Identifier | Comment { recoverWhile=SettingContentRecover }

private SettingContentRecover ::= !(R_BRACKET | COMMA | IDENTIFIER_TOKEN | DATA_TYPE_TOKEN | SETTING_KEY | SETTING_VAL)


// ---- UTILS ----
MapEntry ::= MapKey COLON MapValue { pin=2 }
MapKey ::= Identifier
MapValue ::= BOOLEAN
  | NUMBER
  | STRING
  | MULTI_STRING
  | COLOR
  | ExpressionWrapper
  | InlineReference
  | NULL
  | Identifier

ExpressionWrapper ::= EXPRESSION {
    implements="com.intellij.psi.PsiLanguageInjectionHost"
    mixin="com.puntbyte.dbml.psi.impl.DbmlExpressionMixin"
}

InlineReference  ::= RelationOperator SimpleColumnReference

ColumnReference ::= SimpleColumnReference | CompositeColumnReference

// Left-Factored References (Solves all predictive parsing crashes!)
SimpleColumnReference ::= Identifier DOT Identifier (DOT Identifier)?
CompositeColumnReference ::= Identifier (DOT Identifier)? DOT CompositeColumn

CompositeColumn ::= L_PAREN ColumnList R_PAREN
private ColumnList ::= Identifier (COMMA Identifier)*

RelationOperator ::= OP_ONE_MANY | OP_MANY_ONE | OP_ONE_ONE | OP_MANY_MANY

// ---- THE MAGIC IDENTIFIER RULE ----
Identifier ::=
    IDENTIFIER_TOKEN
  | DATA_TYPE_TOKEN
  | SETTING_KEY
  | SETTING_VAL
  | KW_TABLE | KW_GROUP | KW_PARTIAL | KW_PROJECT | KW_REF | KW_ENUM
  | KW_NOTE | KW_INDEXES | KW_CHECKS | KW_AS
  | BOOLEAN | NULL

private Comment ::= LINE_COMMENT | DOC_COMMENT | BLOCK_COMMENT