{
  parserClass="com.puntbyte.dbml.parser.DbmlParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Dbml"
  psiImplClassSuffix="Impl"
  psiPackage="com.puntbyte.dbml.psi"
  psiImplPackage="com.puntbyte.dbml.psi.impl"
  psiImplUtilClass="com.puntbyte.dbml.psi.impl.DbmlPsiImplUtil"

  elementTypeHolderClass="com.puntbyte.dbml.psi.DbmlTypes"
  elementTypeClass="com.puntbyte.dbml.psi.DbmlElementType"
  tokenTypeClass="com.puntbyte.dbml.psi.DbmlElementType"

  tokens=[
    // Structural
    L_BRACE='{' R_BRACE='}' L_BRACKET='[' R_BRACKET=']' L_PAREN='(' R_PAREN=')'
    COLON=':' DOT='.' COMMA=',' TILDE='~'

    // Operators
    OP_ONE_MANY='<' OP_MANY_ONE='>' OP_ONE_ONE='-' OP_MANY_MANY='<>'

    // Keywords (We list them here so generated DbmlTypes has them)
    KW_TABLE KW_GROUP KW_PARTIAL KW_PROJECT KW_REF KW_ENUM
    KW_NOTE KW_INDEXES KW_CHECKS KW_AS

    // Data
    BOOLEAN NUMBER STRING MULTI_STRING COLOR NULL
    EXPRESSION IDENTIFIER_TOKEN

    // Contextual tokens (from Lexer)
    DATA_TYPE_TOKEN SETTING_KEY SETTING_VAL

    // Comments
    LINE_COMMENT BLOCK_COMMENT DOC_COMMENT
  ]
}

DbmlFile ::= TopLevelItem*

private TopLevelItem ::= ProjectDefinition
  | EnumDefinition
  | TableDefinition
  | ReferenceDefinition
  | GroupDefinition
  | PartialDefinition
  | StickyNoteDefinition
  | Comment

// ---- 1. PROJECT ----
// We use KW_PROJECT token, we don't care if it was "Project" or "project"
ProjectDefinition ::= ProjectKeyword ProjectIdentifier? ProjectBlock
ProjectKeyword ::= KW_PROJECT
ProjectIdentifier ::= Identifier
ProjectBlock ::= L_BRACE ProjectContent* (NoteDefinition)? R_BRACE
ProjectContent ::= MapEntry | Comment

// ---- 2. ENUM ----
EnumDefinition ::= EnumKeyword EnumIdentifierClause EnumBlock
EnumKeyword ::= KW_ENUM
private EnumIdentifierClause ::= (SchemaIdentifier DOT EnumIdentifier) | EnumIdentifier
EnumIdentifier ::= Identifier
EnumBlock ::= L_BRACE EnumValue* R_BRACE
EnumValue ::= (Identifier | STRING) SettingBlock?

SchemaIdentifier ::= Identifier

// ---- 3. TABLE ----
TableDefinition ::= TableKeyword TableIdentifierClause AliasClause? SettingBlock? TableBlock {
   implements="com.intellij.psi.PsiNameIdentifierOwner"
   mixin="com.puntbyte.dbml.psi.impl.DbmlTableDefinitionMixin"
   stubClass="com.puntbyte.dbml.psi.stubs.DbmlTableStub"
   elementTypeFactory="com.puntbyte.dbml.psi.stubs.DbmlStubTypes.getFactory"
}
TableKeyword ::= KW_TABLE
private TableIdentifierClause ::=  (SchemaIdentifier DOT TableIdentifier) | TableIdentifier
TableIdentifier ::= Identifier
TableBlock ::= L_BRACE TableContent* R_BRACE
private TableContent ::=
    ColumnDefinition
  | PartialReference
  | IndexDefinition
  | CheckDefinition
  | NoteDefinition
  | ReferenceDefinition
  | MapEntry
  | Comment

AliasClause ::= AliasKeyword AliasIdentifier
AliasKeyword ::= KW_AS
AliasIdentifier ::= Identifier

// ---- 4. PARTIAL ----
PartialDefinition ::= PartialKeyword PartialIdentifier SettingBlock? PartialBlock {
    implements="com.intellij.psi.PsiNameIdentifierOwner"
    methods=[getName setName getNameIdentifier]
}
PartialKeyword ::= KW_PARTIAL
PartialIdentifier ::= Identifier
PartialBlock ::= L_BRACE PartialContent* R_BRACE
private PartialContent ::= ColumnDefinition | IndexDefinition | NoteDefinition | Comment

PartialReference ::= TILDE PartialIdentifier

// ---- 5. COLUMN ----
// logic: name type [settings]
ColumnDefinition ::= ColumnIdentifier ColumnType SettingBlock?
ColumnIdentifier ::= Identifier
ColumnType ::= DataType (L_PAREN DataLimit R_PAREN)?

DataType ::= Identifier
DataLimit ::= NUMBER (COMMA NUMBER)?

// ---- 6. INDEXES ----
IndexDefinition ::= IndexKeyword IndexBlock
IndexKeyword ::= KW_INDEXES
IndexBlock ::= L_BRACE IndexItem* R_BRACE
IndexItem ::= IndexExpression SettingBlock?
IndexExpression ::= ColumnIdentifier | L_PAREN ColumnList R_PAREN | ExpressionWrapper

// ---- 7. CHECKS ----
CheckDefinition ::= CheckKeyword CheckBlock
CheckKeyword ::= KW_CHECKS
CheckBlock ::= L_BRACE CheckItem* R_BRACE
CheckItem ::= ExpressionWrapper SettingBlock?

// ---- 8. NOTES ----
StickyNoteDefinition ::= NoteKeyword StickyNoteIdentifier? SettingBlock? NoteBlock
StickyNoteIdentifier ::= Identifier?

NoteDefinition ::= NoteKeyword NoteBlock
NoteKeyword ::= KW_NOTE
NoteBlock ::= L_BRACE (STRING | MULTI_STRING) R_BRACE

// ---- 9. REFS ----
ReferenceDefinition ::= ReferenceKeyword ReferenceIdentifier? ReferenceContent
ReferenceKeyword ::= KW_REF
ReferenceIdentifier ::= Identifier
ReferenceContent ::= ReferenceBlock | (COLON ReferenceExpression)
ReferenceBlock ::= L_BRACE ReferenceExpression R_BRACE

ReferenceExpression ::= ColumnReference RelationOperator ColumnReference SettingBlock?

// ---- 10. GROUPS ----
GroupDefinition ::= GroupKeyword GroupIdentifier SettingBlock? GroupBlock
GroupKeyword ::= KW_GROUP
GroupIdentifier ::= Identifier
GroupBlock ::= L_BRACE GroupContent* R_BRACE
GroupContent ::= TableIdentifierClause | NoteDefinition | Comment

// ---- 11. SETTINGS ----
SettingBlock ::= L_BRACKET SettingList R_BRACKET
SettingList ::= SettingContent (COMMA SettingContent)*
SettingContent ::= MapEntry | Identifier | Comment

// ---- UTILS ----
MapEntry ::= MapKey COLON MapValue
MapKey ::= Identifier
MapValue ::= BOOLEAN
  | NUMBER
  | STRING
  | MULTI_STRING
  | COLOR
  | ExpressionWrapper
  | InlineReference
  | NULL
  | Identifier

ExpressionWrapper ::= EXPRESSION {
    implements="com.intellij.psi.PsiLanguageInjectionHost"
    mixin="com.puntbyte.dbml.psi.impl.DbmlExpressionMixin"
}

InlineReference  ::= RelationOperator SimpleColumnReference

ColumnReference ::= SimpleColumnReference | CompositeColumnReference


SimpleColumnReference ::= SchemaIdentifier DOT TableIdentifier DOT ColumnIdentifier
                        | TableIdentifier DOT ColumnIdentifier

CompositeColumnReference ::= SchemaIdentifier DOT TableIdentifier DOT CompositeColumn
                           | TableIdentifier DOT CompositeColumn

CompositeColumn ::= L_PAREN ColumnList R_PAREN
private ColumnList ::= ColumnIdentifier (COMMA ColumnIdentifier)*

RelationOperator ::= OP_ONE_MANY | OP_MANY_ONE | OP_ONE_ONE | OP_MANY_MANY

// ---- THE MAGIC IDENTIFIER RULE ----
// This allows you to name a table "Project", "int", "pk", or "Table"
// It treats keywords as valid identifiers in contexts where a name is expected.
Identifier ::=
    IDENTIFIER_TOKEN
  | DATA_TYPE_TOKEN
  | SETTING_KEY
  | SETTING_VAL
  | KW_TABLE | KW_GROUP | KW_PARTIAL | KW_PROJECT | KW_REF | KW_ENUM
  | KW_NOTE | KW_INDEXES | KW_CHECKS | KW_AS
  | BOOLEAN | NULL

private Comment ::= LINE_COMMENT | DOC_COMMENT | BLOCK_COMMENT